"""
block1_header.py

liberty 파일 맨 위 헤더 주석(Block 1) 작성. GENERATE OPTION 블록은 삭제된 상태
(2026-08 확정).
"""

from __future__ import annotations

import getpass
import time


def _current_user() -> str:
    try:
        import os
        return os.getlogin()
    except OSError:
        return getpass.getuser()


def write_header_block(f_out, library_name: str) -> tuple[str, str, str, str, str]:
    """
    Block 1(헤더 주석)을 쓰고, 이어지는 block2에서 재사용할 (day, month, date, time,
    year) 튜플을 반환한다 (block2의 date/revision 줄이 이 시각과 동일해야 하므로).
    """
    cur_entire_time = time.ctime()
    cur_day, cur_month, cur_date, cur_time, cur_year = cur_entire_time.split()

    f_out.write("/**************************************************\n")
    f_out.write(" * This liberty is generated by liberty_generator\t*\n")
    f_out.write(
        " * Date\t: {day} {month} {date} {time} {year}\t\t\t*\n".format(
            day=cur_day, month=cur_month, date=cur_date, time=cur_time, year=cur_year
        )
    )
    f_out.write(f" * Written by\t: {_current_user()}\t\t\t\t\t*\n")
    f_out.write(" **************************************************/\n")
    f_out.write("\n")
    f_out.write("/************************************************\n")
    f_out.write(f" * LIBRARY : {library_name}\t\t\t\t*\n")
    f_out.write(f" * LIBRARY FAMILY : {library_name}\t\t\t*\n")
    f_out.write(" * ADB VERSION : 3111\t\t\t\t*\n")
    f_out.write(
        " * DATE    : {day} {month} {date} {time} {year}\t\t*\n".format(
            day=cur_day, month=cur_month, date=cur_date, time=cur_time, year=cur_year
        )
    )
    f_out.write(" * TECHNOLOGY FILE REVISION : 1.000\t\t*\n")
    f_out.write(" * VENDOR  : Samsung Electronics      \t\t*\n")
    f_out.write(" * VERSION : 2.335\t\t\t\t*\n")
    f_out.write(" * HAZARD MARGIN : 0.00000\t\t\t*\n")
    f_out.write(" ************************************************/\n")
    f_out.write("\n")

    return cur_day, cur_month, cur_date, cur_time, cur_year
